
language: csharp
dotnet: '2.0.0'
mono: none

cache:
  directories:
    - $HOME/Library/Caches/Homebrew

matrix:
  include:
    - os: osx
      osx_image: xcode9.1
      before_install:
        - brew update
        - brew tap caskroom/cask
        - brew cask install powershell
    - os: linux
      dist: trusty
      # VM-based builds turned out to be faster
      sudo: required
      addons:
        apt:
          sources:
            - sourceline: deb [arch=amd64] https://packages.microsoft.com/ubuntu/14.04/prod trusty main
              key_url: https://packages.microsoft.com/keys/microsoft.asc
          packages:
            - powershell

script:
  - pwsh -c 'Import-Module ./PSSourcegraph.psd1'

deploy:
  provider: script
  script: pwsh -c 'Publish-Module -Path . -NuGetApiKey $NUGET_API_KEY'
  on:
    tags: true
